/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CharacterPositionNapiValue {
  line: number
  column: number
}
export interface ComponentPropNapiValue {
  name: string
  defaultValue?: string
  start: CharacterPositionNapiValue
  end: CharacterPositionNapiValue
}
export interface HtmlElementSpanNapiValue {
  start: CharacterPositionNapiValue
  end: CharacterPositionNapiValue
}
export interface HtmlElementUsageNapiValue {
  tag: string
  count: number
  spans: Array<HtmlElementSpanNapiValue>
}
export interface ComponentNapiValue {
  id: string
  exportIds: Array<string>
  name: string
  source: string
  createdAt?: number
  updatedAt?: number
  dependencies: Array<string>
  props: Array<ComponentPropNapiValue>
  htmlElements: Array<string>
  htmlElementUsages: Array<HtmlElementUsageNapiValue>
  start?: CharacterPositionNapiValue
  end?: CharacterPositionNapiValue
}
export interface ExportNapiValue {
  name: string
  moduleId: string
  createdAt?: number
  updatedAt?: number
  inferredType?: string
  resolvedType?: string
  traceToDeclaration: Array<string>
  isComponent: boolean
}
export interface AnalyzerResultNapiValue {
  components: Array<ComponentNapiValue>
  exports: Array<ExportNapiValue>
  errors: Array<string>
  stats: string
}
export interface PackageData {
  name: string
  version: string
  path: string
  aliases: Record<string, Array<string>>
  importMap: Record<string, Array<string>>
  exportMap: Record<string, Array<string>>
}
export interface PathResolutionEntry {
  name: string
  patterns: Array<string>
  type: string
  sourcePath: string
}
export interface ResolutionConfigIssue {
  packageName: string
  entry: PathResolutionEntry
  type: string
  level: string
}
export interface ProjectSetupExternal {
  root: PackageData
  packages: Record<string, PackageData>
  absolutePath: string
}
export function analyze(projectRoot: string, repoRoot: string, inputPatterns: Array<string>, ignorePatterns: Array<string>, logLevel: string | undefined | null, logFilePath: string | undefined | null, projectSetup: ProjectSetupExternal, gitHistoryLimit: number): Promise<AnalyzerResultNapiValue>
export function parse(projectRoot: string, repoRoot: string, inputPatterns: Array<string>, ignorePatterns: Array<string>, logLevel: string | undefined | null, logFilePath: string | undefined | null, projectSetup: ProjectSetupExternal, gitHistoryLimit: number): Promise<string>
export function analyzePartial(projectRoot: string, modifiedFiles: Array<string>, relatedFiles: Array<string>, ignorePatterns: Array<string>, projectSetup: ProjectSetupExternal): Promise<AnalyzerResultNapiValue>
